if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js');}
const views=['home','apply','checkin','training','ranks','promote','profile'];
function goto(v){views.forEach(id=>document.getElementById('view-'+id)?.classList.add('hidden'));document.getElementById('view-'+v)?.classList.remove('hidden');if(v==='ranks')renderRanks();if(v==='checkin')renderCheckIns();if(v==='home')renderHome();if(v==='profile')renderProfile();}
const RANKS=[{rank:'E-1 Recruit',days:0,req:'—'},{rank:'E-2 Private',days:30,req:'—'},{rank:'E-3 PFC',days:65,req:'—'},{rank:'E-4 Specialist/Corporal',days:100,req:'—'},{rank:'E-5 Sergeant',days:145,req:'Leadership + Basic Medical + Basic Land Nav + FTL Board approval'},{rank:'E-6 Staff Sergeant',days:205,req:'Recruitment Course'},{rank:'E-7 Sergeant First Class',days:280,req:'—'},{rank:'E-8 Master Sergeant / 1SG',days:370,req:'—'},{rank:'E-9 Sergeant Major',days:490,req:'NINE‑LINE MEDEVAC certified'}];
const db={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let ME=null;async function fetchMe(){try{const r=await fetch('/api/user',{credentials:'include'});ME=await r.json();renderAuth()}catch(e){console.error(e)}}function renderAuth(){const l=document.getElementById('btn-login'),o=document.getElementById('btn-logout'),t=document.getElementById('me-tag');if(ME?.loggedIn){l?.classList.add('hidden');o?.classList.remove('hidden');if(t)t.textContent=`${ME.user.username}#${ME.user.discriminator}`}else{l?.classList.remove('hidden');o?.classList.add('hidden');if(t)t.textContent='Not signed in'}}
function loginDiscord(){location.href='/api/auth/discord'}async function logout(){document.cookie='erg_sess=; Max-Age=0; path=/;';await fetchMe()}
function daysActive(){const p=db.get('profile',{});if(!p.enlistDate)return db.get('daysOverride',0);return Math.max(0,Math.floor((Date.now()-new Date(p.enlistDate))/86400000))}
function renderHome(){document.getElementById('kpi-days').textContent=daysActive();let c='E-1 Recruit';const d=daysActive();for(const r of RANKS){if(d>=r.days)c=r.rank}document.getElementById('kpi-rank').textContent=c}
function setDaysOverride(){const n=parseInt(prompt('Set days active override:')||'0',10);db.set('daysOverride',isNaN(n)?0:n);renderHome();renderRanks()}
function val(id){return document.getElementById(id).value.trim()}function setv(id,v){document.getElementById(id).value=v||''}function byId(id){return document.getElementById(id)}
function saveProfile(){const p={name:val('p-name'),callsign:val('p-callsign'),platform:val('p-platform'),timezone:val('p-timezone'),discordId:(ME?.loggedIn&&ME.user?.id)?ME.user.id:val('p-discord'),enlistDate:val('p-enlist')};db.set('profile',p);alert('Profile saved');renderHome()}
function renderProfile(){const p=db.get('profile',{});setv('p-name',p.name);setv('p-callsign',p.callsign);setv('p-platform',p.platform||'Xbox');setv('p-timezone',p.timezone);setv('p-discord',p.discordId);setv('p-enlist',p.enlistDate)}
function saveApplication(){const a={availability:val('app-avail'),experience:val('app-exp'),preferredFT:val('app-ft'),notes:val('app-notes'),ts:Date.now()};db.set('application',a);alert('Application saved.')}
async function sendAppServer(){const r=await fetch('/api/submit/application',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(db.get('application',{})),credentials:'include'});alert(r.ok?'Application submitted.':'Sign in first.')}
function saveCheckIn(){const arr=db.get('checkins',[]);const week=val('ci-week');if(!week){alert('Choose a date');return}arr.unshift({week,acts:val('ci-acts'),issues:val('ci-issues'),ts:Date.now()});db.set('checkins',arr);renderCheckIns();alert('Check‑in saved.')}
function renderCheckIns(){const arr=db.get('checkins',[]);const tbody=document.querySelector('#ci-table tbody');if(!tbody)return;tbody.innerHTML='';arr.forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${r.week}</td><td>${(r.acts||'').slice(0,120)}${(r.acts||'').length>120?'…':''}</td>`;tbody.appendChild(tr)})}
async function sendLastCheckInServer(){const arr=db.get('checkins',[]);if(!arr.length){alert('No check‑ins yet');return}const r=await fetch('/api/submit/checkin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(arr[0]),credentials:'include'});alert(r.ok?'Check‑in submitted.':'Sign in first.')}
function saveTraining(){const t={lead:byId('t-lead').checked,med:byId('t-med').checked,nav:byId('t-nav').checked,recruit:byId('t-recruit').checked,nine:byId('t-nine').checked,notes:val('t-notes')};db.set('training',t);alert('Training saved.')}
async function sendTrainingServer(){const r=await fetch('/api/submit/training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(db.get('training',{})),credentials:'include'});alert(r.ok?'Training submitted.':'Sign in first.')}
function renderRanks(){const d=daysActive();const body=document.getElementById('rank-body');if(!body)return;body.innerHTML='';RANKS.forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${r.rank}</td><td>${r.days}</td><td>${r.req}</td>`;if(d>=r.days)tr.style.color='#22c55e';body.appendChild(tr)})}
function exportPromotion(){const p=db.get('profile',{});const t=db.get('training',{});const pay={desiredRank:val('pr-rank'),statement:val('pr-statement'),profile:p,training:t,ts:Date.now()};const blob=new Blob([JSON.stringify(pay,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='erg_promotion_request.json';a.click();URL.revokeObjectURL(url)}
async function sendPromotionServer(){const r=await fetch('/api/submit/promotion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({desiredRank:val('pr-rank'),statement:val('pr-statement')}),credentials:'include'});alert(r.ok?'Promotion submitted.':'Sign in first.')}
fetchMe().then(()=>{goto('home');renderHome();renderCheckIns();renderRanks();renderProfile()});